#!/usr/bin/env node
// Vendors src/motion/sources/emageSeed.ts as plain JS (js/vendor/emageSeed.mjs) so the published package is
// self-contained. Node refuses to type-strip .ts files under node_modules, hence the .mjs copy.
// Runs automatically as `prepack`; in-repo runs keep importing the .ts source directly (see common.mjs).
import fs from 'node:fs';
import path from 'node:path';
import { stripTypeScriptTypes } from 'node:module';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, '../../../src/motion/sources/emageSeed.ts');
const dst = path.join(here, 'vendor/emageSeed.mjs');
fs.mkdirSync(path.dirname(dst), { recursive: true });
fs.writeFileSync(dst, `// GENERATED by js/sync-seed.mjs from src/motion/sources/emageSeed.ts. Do not edit.\n` + stripTypeScriptTypes(fs.readFileSync(src, 'utf8')));
console.log(`wrote ${path.relative(process.cwd(), dst)}`);
