/**
 * Project XiaoChun 全局配置中心 (Single Source of Truth)
 */
import * as THREE from 'three';
export * from './types/config';
import type {
  LightConfig,
  SceneRegistryConfig,
  MaterialSaturationConfig,
  VrmOutlineConfig,
  VrmMToonConfig,
  EmageMotionConfig,
  BodyMorphConfig,
  ModelPartCategoryDefinition,
  ModelPartDefinition,
  AddonDefinition,
} from './types/config';

export const POSTFX_TONE_MAPPING_MODE = {
  NEUTRAL: THREE.NeutralToneMapping,
  ACES_FILMIC: THREE.ACESFilmicToneMapping,
  LINEAR: THREE.LinearToneMapping,
} as const;

// INT8 量化开关：useInt8 = true 加载 _int8.onnx 模型
const useInt8 = true;
const q = (fp32: string) => (useInt8 ? fp32.replace('.onnx', '_int8.onnx') : fp32);

export const APP_CONFIG = {
  brand: {
    name: 'Project XiaoChun',
    logo: '/logo.png',
    favicon: '/favicon.png',
    github: 'https://github.com/FireTable/project-xiaochun',
  },
  api: {
    baseUrl: (import.meta.env?.VITE_API_BASE_URL as string | undefined) ?? 'https://xiaochun.firetable.tech',
  },
  model: {
    defaultSource: '/vrm/xiaochun_base.vrmbase',
    defaultName: 'XiaoChun',
    defaultSha: 'e99fcc335a512b5a',
    spawn: { x: 0, y: 0, z: -4 },
    addons: {
      'xiaochun_techwear': {
        source: '/vrm/addons/xiaochun_techwear.vrmaddon',
        name: 'XiaoChun Techwear',
        sha: '5b82a059455ce7bc',
        bodyMorph: {
          shoulderWidth: 1,
          buttocks: 1.2,
          bust: 1.1,
          bustThickness: 1,
          bustPitch: 0,
        },
      },
      'xiaochun_cheongsam': {
        source: '/vrm/addons/xiaochun_cheongsam.vrmaddon',
        name: 'XiaoChun Cheongsam',
        sha: 'c2bf3c1591a5a22a',
        bodyMorph: {
          waist: 0.74,
          bust: 1.2,
          bustThickness: 1.04,
          bustPitch: 0.03,
          bustSpread: -0.012,
        },
      },
      'xiaochun_bikini': {
        source: '/vrm/addons/xiaochun_bikini.vrmaddon',
        name: 'XiaoChun Bikini',
        sha: '92d19fdee413d436',
        bodyMorph: {
          shoulderWidth: 0.95,
          buttocks: 1.16,
          buttocksPitch: 0.15,
          bustThickness: 1.12,
          bustPitch: -0.04,
          bustSpread: -0.02,
        },
      },
      'xiaochun_maid': {
        source: '/vrm/addons/xiaochun_maid.vrmaddon',
        name: 'XiaoChun Maid',
        sha: '318e2d2914d76b4d',
        bodyMorph: {
          shoulderWidth: 1.4,
          waist: 0.7,
        },
      },
      'xiaochun_swimsuit': {
        source: '/vrm/addons/xiaochun_swimsuit.vrmaddon',
        name: 'XiaoChun Swimsuit',
        sha: 'b7511150c85ce0c1',
        bodyMorph: {
          shoulderWidth: 1.38,
          bustPitch: 0.0,
          bustSpread: -0.018,
        },
      },
      'xiaochun_shroud': {
        source: '/vrm/addons/xiaochun_shroud.vrmaddon',
        name: 'XiaoChun Shroud',
        sha: 'f4a49a7ae2cd2dc5',
        bodyMorph: {
          waist: 0.72,
          belly: 0.81,
          bust: 1.18,
          bustThickness: 1.06,
          bustPitch: 0,
          thighs: 0.98,
        },
      },
      'xiaochun_dinner_dress': {
        source: '/vrm/addons/xiaochun_dinner_dress.vrmaddon',
        name: 'XiaoChun Dinner Dress',
        sha: 'bc2e42f754e635af',
        default: true,
        bodyMorph: {
          shoulderWidth: 1.05,
          waist: 0.7,
          bustPitch: 0.01,
          bustSpread: -0.024,
        },
      },
      'xiaochun_office_lady': {
        source: '/vrm/addons/xiaochun_office_lady.vrmaddon',
        name: 'XiaoChun Office Lady',
        sha: '7d4f1f5c98bb0434',
        bodyMorph: {
          shoulderWidth: 0.96,
          waist: 0.82,
          bust: 1.02,
          bustPitch: 0.19,
          bustSpread: -0.018,
        },
      },
      'xiaochun_wedding': {
        source: '/vrm/addons/xiaochun_wedding.vrmaddon',
        name: 'XiaoChun Wedding',
        sha: '3214c9a2cb40d310',
        bodyMorph: {
          shoulderWidth: 1.2,
          torsoThickness: 0.8,
          waist: 0.66,
          bust: 1.1,
          bustSpread: -0.016,
        },
      },
    } as Record<string, AddonDefinition>,
  },
  emage: {
    base: Boolean(import.meta.env?.PROD)
      ? ((import.meta.env?.VITE_EMAGE_BASE_PROD as string | undefined) ?? 'https://cdn.firetable.tech/xiaochun')
      : ((import.meta.env?.VITE_EMAGE_BASE as string | undefined) ?? '/onnx'),
    cacheName: 'emage-models-v1',
    models: {
      step: { file: q('emage_step.onnx'), enabled: true, label: 'step (autoregressive temporal)' },
      vqUpper: { file: q('vq_upper_idx.onnx'), enabled: true, label: 'vq_upper (head/neck/shoulders 78D)' },
      vqHands: { file: q('vq_hands_idx.onnx'), enabled: true, label: 'vq_hands (30 finger joints 180D)' },
      vqLower: { file: q('vq_lower_idx.onnx'), enabled: true, label: 'vq_lower (legs/hips/spine 61D)' },
      postprocess: { file: q('postprocess.onnx'), enabled: true, label: 'postprocess (VQ heads → 6D rot)' },
      vqFace: { file: q('vq_face.onnx'), enabled: false, label: 'vq_face (jaw + face 106D, disabled)' },
      vqGlobal: { file: q('vq_global.onnx'), enabled: false, label: 'vq_global (root translation 61D, disabled)' },
    } satisfies Record<string, { file: string; enabled: boolean; label: string }>,
    motion: {
      gestureIntensity: 1.0,
      fingerIntensity: 0.5,
      torsoIntensity: 0.75,
      spineIntensity: 0.3,
      hipIntensity: 0.70,
      legIntensity: 0.40,
      footIkIdlePlant: 0.92,
      headIntensity: 0.80,
      dampingStiffness: 6.5,
      temporalSmoothRadius: 12,
      chunkSeamMaxFrames: 14,
      streamingCatchUpRate: 1.08,
      advanceFrames: 64,
      fadeInDuration: 0.60,
      switchSegmentCrossFade: 0.24,
      poseMicroFadeJumpDiv: 1.15,
      poseMicroFadeMinSec: 0.05,
      poseMicroFadeMaxSec: 0.36,
      poseMicroFadeJumpMin: 0.015,
      seamJumpThreshold: 0.02,
      seamJumpFramesScale: 0.015,
      vqSampleTemperature: 0.85,
      vqSampleTopK: 6,
    } as EmageMotionConfig,
  },
  stt: {
    base: Boolean(import.meta.env?.PROD)
      ? ((import.meta.env?.VITE_STT_BASE_PROD as string | undefined) ??
        'https://cdn.firetable.tech/xiaochun/stt/sensevoice-zh-en-ja-ko-yue-int8-2024-07-17')
      : ((import.meta.env?.VITE_STT_BASE as string | undefined) ??
        'https://cdn.firetable.tech/xiaochun/stt/sensevoice-zh-en-ja-ko-yue-int8-2024-07-17'),
    cacheName: 'xiaochun-stt-v2024-07-17',
    cacheKeyPrefix: 'xiaochun-stt/v2024-07-17',
    modelFile: 'model.int8.onnx',
    tokensFile: 'tokens.txt',
    useItn: true,
    vadSilenceMs: 600,
    vadMaxMs: 20_000,
    sampleRate: 16_000,
    vadStartThreshold: 0.014,
    vadSilenceThreshold: 0.008,
    vadStartMs: 80,
    vadPrerollMs: 300,
    minUtteranceMs: 250,
  },
  llm: {
    model: 'MiniCPM5-2B-q4f16_1-MLC',
    fallback: 'Qwen2.5-0.5B-Instruct-q4f16_1-MLC',
    thinking: false,
  },
  memory: {
    shortTermTurns: 2,
    turnMaxChars: 120,
    userTurnsMin: 1,
    userTurnsMax: 50,
  },
  chat: {
    showHeadBubble: true as boolean,
  },
  camera: {
    defaultFov: 30,
    minFov: 15,
    maxFov: 60,
    defaultPosition: [0.0, 0.95, 2.2] as [number, number, number],
    defaultTarget: [0.0, 0.9, 0.0] as [number, number, number],
    defaultShotExtent: 1.34,
    defaultMinDistance: 1.0,
    defaultMaxDistance: 15.0,
    defaultEnableBodyTurn: true as boolean,
    defaultEnableGaze: true as boolean,
    minPolarAngle: 0.01,
    maxPolarAngle: Math.PI - 0.01,
    pitchSensitivityY: 0.0065,
  },
  interaction: {
    characterTurnSensitivityX: 0.0102,
    cameraYGuide: { xOffset: -0.38 },
    guideColor: '#ffffff',
  },
  bodyTurn: {
    turnStartThreshold: 0.42,
    turnStopThreshold: 0.20,
    springK: 5.95,
    maxYawVel: 2.6,
    phaseDuration: { idle: 0, lift: 0.21, swing: 0.16, plant: 0.09, settle: 0.21 },
    stepLowerLegBend: 0.48,
    stepUpperLegLift: 0.24,
    stepAnkleFlex: 0.12,
    hipSwayAmount: 0.012,
    hipRollAmount: 0.012,
    hipYawAmount: 0.012,
    hipBounceAmount: 0.036,
  },
  gaze: {
    maxHeadTurnSpeed: 4.2,
    fovComfortHalfAngle: 1.57,
    fovBlindHalfAngle: 2.35,
    trackSpeed: 10.0,
  },
  springBone: {
    bust: { stiffness: 0.22, dragForce: 0.26, gravityPower: 0.005, hitRadius: 0.0232 },
    skirt: { stiffness: 0.35, dragForce: 0.18, gravityPower: 0.10, hitRadius: 0.018 },
    ribbon: { stiffness: 0.42, dragForce: 0.16, gravityPower: 0.005, hitRadius: 0.025 },
  },
  wind: {
    mouseRadius: 0.58,
    wakeRadius: 0.95,
    mouseWindStrength: 0.32,
    wakeStrengthRatio: 0.12,
    mouseSpeedReference: 2000,
    mouseSpeedSmoothing: 0.35,
    skirtMultiplier: 1.45,
    ribbonMultiplier: 1.35,
    idleTimeoutMs: 120,
    bust: { sensitivity: 0.23, speedExponent: 0.85, impulseBonus: 1.35 },
  },
  renderer: {
    maxPixelRatioMobile: 2.75,
    maxPixelRatioDesktop: 3,
    targetFpsMobile: 40,
    targetFpsDesktop: 60,
  },
  scene: {
    theme: 'light' as 'light' | 'dark',
  },
  shadow: {
    planeSize: 12,
    planeY: 0.0005,
    opacityDark: 0.50,
    opacityLight: 0.40,
    softShadow: {
      enabled: true,
      radialStops: [
        { pos: 0.00, alpha: 1.00 },
        { pos: 0.03, alpha: 0.70 },
        { pos: 0.06, alpha: 0.30 },
        { pos: 0.09, alpha: 0.00 },
        { pos: 1.00, alpha: 0.00 },
      ],
      edgeFadeStart: 0.5,
      edgeFadeEnd: 0.8,
    },
  },
  scenes: {
    defaultSceneId: 'light',
    items: {
      light: {
        id: 'light',
        nameKey: 'header.switchScene.light',
        icon: 'Sun',
        lineworkTheme: 'light',
        isTransparent: false,
        components: { topHeader: true, chatBar: true, headBubble: true, heightRuler: true, dropZone: true },
        tauri: { resizable: true, cornerHandles: false },
      },
      dark: {
        id: 'dark',
        nameKey: 'header.switchScene.dark',
        icon: 'Moon',
        lineworkTheme: 'dark',
        isTransparent: false,
        components: { topHeader: true, chatBar: true, headBubble: true, heightRuler: true, dropZone: true },
        tauri: { resizable: true, cornerHandles: false },
      },
      transparent: {
        id: 'transparent',
        nameKey: 'header.switchScene.transparent',
        icon: 'Ghost',
        lineworkTheme: 'transparent',
        isTransparent: true,
        components: { topHeader: true, chatBar: true, headBubble: true, heightRuler: false, dropZone: true },
        tauri: { resizable: false, cornerHandles: true },
      },
    },
  } as SceneRegistryConfig,
  lights: {
    dir: { base: 1.10, enabled: true },
    hemi: { base: 0.80, enabled: true },
    fill: { base: 0.65, enabled: true },
    globalMult: 1.0,
  } as LightConfig,
  postfx: {
    enabled: true,
    bloom: { strength: 0.045, radius: 0.36, threshold: 0.76 },
    vignette: { darkness: 0.0, offset: 0.5 },
    toneMapping: { mode: THREE.LinearToneMapping, exposure: 1.06 },
    bc: { brightness: 0.0, contrast: 0.035 },
    hs: { hue: 0.0, saturation: 0.01 },
    bloomInputScaleMobile: 0.3,
    bloomInputScaleDesktop: 0.5,
    composerMSAASamplesMobile: 3,
    composerMSAASamplesDesktop: 4,
  },
  saturation: {
    default: {
      preset: 'custom',
      clothing: 1.05,
      hair: 1.35,
      eyes: 1.35,
      skin: 1.02,
    } as MaterialSaturationConfig,
    presets: {
      vibrant: { preset: 'vibrant', clothing: 1.12, hair: 1.25, eyes: 1.25, skin: 1.04 } as MaterialSaturationConfig,
      sweet: { preset: 'sweet', clothing: 1.05, hair: 1.18, eyes: 1.20, skin: 1.02 } as MaterialSaturationConfig,
      cinematic: { preset: 'cinematic', clothing: 0.95, hair: 1.05, eyes: 1.10, skin: 0.98 } as MaterialSaturationConfig,
      original: { preset: 'original', clothing: 1.0, hair: 1.0, eyes: 1.0, skin: 1.0 } as MaterialSaturationConfig,
    },
  },
  outline: {
    enabled: true,
    widthMode: 'screenCoordinates',
    widthFactor: 0.0016,
    color: '#968890',
    lightingMix: 0.25,
  } as VrmOutlineConfig,
  mtoon: {
    skin: {
      face: {
        shadeShift: 0.0,
        shadeToony: 0.85,
        shadeColor: '#ede0ea', // 高明度纯净粉紫阴影
        litColor: '#ffffff', // 纯正白皙高光面
        rimLightingMix: 0.08,
        rimColor: '#fff0ea',
        rimFresnelPower: 5.5,
        rimLift: 0.03,
      },
      body: {
        shadeShift: -0.01,
        shadeToony: 0.82,
        shadeColor: '#e8d8e3', // 清透粉紫阴影
        litColor: '#ffffff', // 纯白受光面
        rimLightingMix: 0.16,
        rimColor: '#fff0ea',
        rimFresnelPower: 4.2,
        rimLift: 0.04,
      },
      polygonOffset: { enabled: false, factor: 0.0, units: 0.0 },
    },
    socks: {
      npr: {
        shadeShift: -0.05,
        shadeToony: 0.80,
        rimLightingMix: 0.60,
        rimColor: '#ffffff',
        rimFresnelPower: 3.0,
        rimLift: 0.15,
      },
      polygonOffset: { enabled: true, factor: -1.0, units: -4.0 },
    },
    cloth: {
      npr: {
        shadeShift: 0.0,
        shadeToony: 0.85,
        shadeColor: '#e6e2ed', // 清透微冷灰紫布料阴影
        rimLightingMix: 0.35,
        rimColor: '#ffffff',
        rimFresnelPower: 4.0,
        rimLift: 0.10,
      },
      innerPolygonOffset: { enabled: true, factor: -1.0, units: -2.0 },
      outerPolygonOffset: { enabled: true, factor: -3.0, units: -10.0 },
    },
    parts: {
      enabled: true,
      shadow2ndColor: [0.82, 0.76, 0.85] as [number, number, number],
      shadow3rdColor: [0.65, 0.60, 0.72] as [number, number, number],
      faceShadow2ndColor: [0.88, 0.82, 0.90] as [number, number, number],
      face: {
        softMix: 0.55,
        blurBoost: 0.32,
        shadowBorder: 0.48,
        shadowBlur: 0.32,
        shadow2ndStrength: 0.0,
        shadow2ndBorder: 0.3,
        shadow2ndBlur: 0.3,
        shadow3rdStrength: 0.0,
        shadow3rdBorder: 0.12,
        shadow3rdBlur: 0.26,
        rimBoost: 1.35,
        rimBorder: 0.45,
        rimBlur: 0.2,
        rimDirStrength: 0.28,
        rimMainStrength: 0.35,
        rimShadowMask: 0.4,
        hairSpecStrength: 0.0,
        clothSpecStrength: 0.0,
        skinSpecStrength: 0.0,
        skinSpecPower: 36,
        skinSpecFresnel: 0.0,
        skinSpecColor: [1.0, 0.97, 0.95],
        ambientLift: 0.12,
        shadeMainStrength: 0.18,
        matcap2ndStrength: 0.0,
        specularStrength: 0.0,
        specularPower: 36,
        specularBorder: 0.42,
        specularBlur: 0.22,
        reflectStrength: 0.0,
        reflectFresnel: 0.5,
        reflectMetallic: 0.0,
        reflectSmoothness: 0.45,
        backlightStrength: 0.0,
        backlightColor: [1.0, 0.82, 0.75],
        rimFresnelPower: 3.2,
        rimIndirStrength: 0.0,
        matcap2ndContrast: 1.0,
        matcap2ndScale: 1.05,
        emissionBoost: 0.0,
        distanceFade: 0.15,
        faceSoft: 0.25,
        normalSkinBoost: 0.0,
        envStrength: 0.08,
        gemFresnel: 0.0,
        outlineMix: 0.0,
        receiveShadowRate: 0.0,
      },
      body: {
        softMix: 0.6,
        blurBoost: 0.34,
        shadowBorder: 0.5,
        shadowBlur: 0.34,
        shadow2ndStrength: 0.0,
        shadow2ndBorder: 0.32,
        shadow2ndBlur: 0.32,
        shadow3rdStrength: 0.0,
        shadow3rdBorder: 0.14,
        shadow3rdBlur: 0.28,
        rimBoost: 1.4,
        rimBorder: 0.46,
        rimBlur: 0.2,
        rimDirStrength: 0.32,
        rimMainStrength: 0.3,
        rimShadowMask: 0.35,
        hairSpecStrength: 0.0,
        clothSpecStrength: 0.0,
        skinSpecStrength: 0.0,
        skinSpecPower: 38,
        skinSpecFresnel: 0.0,
        skinSpecColor: [1.0, 0.96, 0.94],
        ambientLift: 0.10,
        shadeMainStrength: 0.22,
        matcap2ndStrength: 0.0,
        specularStrength: 0.0,
        specularPower: 32,
        specularBorder: 0.4,
        specularBlur: 0.24,
        reflectStrength: 0.0,
        reflectFresnel: 0.55,
        reflectMetallic: 0.0,
        reflectSmoothness: 0.5,
        backlightStrength: 0.0,
        backlightColor: [1.0, 0.8, 0.72],
        rimFresnelPower: 3.0,
        rimIndirStrength: 0.0,
        matcap2ndContrast: 1.4,
        matcap2ndScale: 1.08,
        emissionBoost: 0.0,
        distanceFade: 0.12,
        faceSoft: 0.0,
        normalSkinBoost: 0.0,
        envStrength: 0.08,
        gemFresnel: 0.0,
        outlineMix: 0.0,
        receiveShadowRate: 1.0,
      },
      hair: {
        softMix: 0.0,
        blurBoost: 0.0,
        shadowBorder: -1.0,
        shadowBlur: 0.0,
        shadow2ndStrength: 0.0,
        shadow3rdStrength: 0.0,
        rimBoost: 1.0,
        rimBorder: 0.0,
        rimBlur: 0.0,
        rimDirStrength: 0.0,
        rimMainStrength: 0.0,
        rimShadowMask: 0.0,
        hairSpecStrength: 0.0,
        hairSpecPower: 56,
        hairSpecShift: -0.1,
        clothSpecStrength: 0.0,
        skinSpecStrength: 0.0,
        ambientLift: 0.0,
        shadeMainStrength: 0.0,
        matcap2ndStrength: 0.0,
        specularStrength: 0.0,
        reflectStrength: 0.0,
        reflectFresnel: 0.0,
        reflectSmoothness: 0.0,
        backlightStrength: 0.0,
        rimFresnelPower: 0.0,
        rimIndirStrength: 0.0,
        matcap2ndContrast: 1.0,
        matcap2ndScale: 1.0,
        faceSoft: 0.0,
        normalSkinBoost: 0.0,
        envStrength: 0.0,
        gemFresnel: 0.0,
        outlineMix: 0.0,
        receiveShadowRate: 1.0,
        fabricSheenStrength: 0.35,
        fabricSheenPower: 3.5,
        fabricSheenColor: [1.0, 0.92, 0.88],
      },
      eyes: {
        softMix: 0.7,
        blurBoost: 0.12,
        shadow2ndStrength: 0.0,
        shadow3rdStrength: 0.0,
        rimBoost: 1.0,
        rimBorder: 0.55,
        rimBlur: 0.12,
        rimDirStrength: 0.12,
        rimMainStrength: 0.1,
        rimShadowMask: 0.2,
        hairSpecStrength: 0.0,
        clothSpecStrength: 0.0,
        skinSpecStrength: 0.0,
        ambientLift: 0.05,
        shadeMainStrength: 0.15,
        matcap2ndStrength: 0.0,
        reflectStrength: 0.0,
        matcap2ndContrast: 1.15,
        faceSoft: 0.0,
        envStrength: 0.05,
        gemFresnel: 0.0,
        outlineMix: 0.0,
      },
      cloth: {
        softMix: 0.82,
        blurBoost: 0.3,
        shadowBorder: 0.5,
        shadowBlur: 0.16,
        shadow2ndStrength: 0.2,
        shadow2ndBorder: 0.32,
        shadow2ndBlur: 0.28,
        shadow3rdStrength: 0.0,
        shadow3rdBorder: 0.14,
        shadow3rdBlur: 0.26,
        rimBoost: 1.22,
        rimBorder: 0.5,
        rimBlur: 0.16,
        rimDirStrength: 0.35,
        rimMainStrength: 0.2,
        rimShadowMask: 0.3,
        hairSpecStrength: 0.0,
        clothSpecStrength: 0.0,
        clothSpecPower: 88,
        clothSpecDarkLuma: 0.0,
        clothSpecDarkBoost: 0.0,
        skinSpecStrength: 0.0,
        ambientLift: 0.05,
        shadeMainStrength: 0.3,
        matcap2ndStrength: 0.0,
        specularStrength: 0.0,
        specularPower: 64,
        specularBorder: 0.5,
        specularBlur: 0.12,
        reflectStrength: 0.0,
        reflectFresnel: 0.6,
        reflectMetallic: 0.0,
        reflectSmoothness: 0.55,
        backlightStrength: 0.0,
        rimFresnelPower: 2.8,
        rimIndirStrength: 0.0,
        matcap2ndContrast: 1.45,
        matcap2ndScale: 1.12,
        faceSoft: 0.0,
        normalSkinBoost: 0.0,
        envStrength: 0.18,
        gemFresnel: 0.0,
        outlineMix: 0.0,
      },
      socks: {
        softMix: 0.8,
        blurBoost: 0.28,
        shadow2ndStrength: 0.1,
        shadow3rdStrength: 0.0,
        rimBoost: 1.15,
        rimBorder: 0.5,
        rimBlur: 0.16,
        rimDirStrength: 0.28,
        rimMainStrength: 0.2,
        rimShadowMask: 0.28,
        hairSpecStrength: 0.0,
        clothSpecStrength: 0.0,
        clothSpecPower: 72,
        skinSpecStrength: 0.0,
        ambientLift: 0.1,
        shadeMainStrength: 0.28,
        matcap2ndStrength: 0.0,
        specularStrength: 0.0,
        reflectStrength: 0.0,
        reflectFresnel: 0.45,
        backlightStrength: 0.0,
        faceSoft: 0.0,
        envStrength: 0.14,
        gemFresnel: 0.0,
        outlineMix: 0.0,
      },
    },
  } as unknown as VrmMToonConfig,
  bodyMorph: {
    default: {
      overallScale: 1.00,
      head: 0.98,
      neck: 0.96,
      neckDepth: 1.00,
      neckLength: 1.00,
      shoulderWidth: 1.10,
      torsoLength: 0.92,
      torsoThickness: 0.88,
      waist: 0.86,
      belly: 0.80,
      hips: 1.00,
      buttocks: 1.13,
      buttocksThickness: 1.00,
      buttocksPitch: 0.02,
      buttocksSpread: 0.002,
      bust: 1.24,
      bustThickness: 1.08,
      bustPitch: 0.06,
      bustSpread: -0.032,
      arms: 0.86,
      armLength: 1.00,
      hands: 1.00,
      fingerWidth: 0.96,
      thighs: 1.02,
      thighLength: 1.00,
      calves: 0.82,
      calfLength: 1.00,
      feet: 0.96,
    } as BodyMorphConfig,
    limits: {
      overallScale: { min: 0.70, max: 1.30, step: 0.01 },
      head: { min: 0.85, max: 1.20, step: 0.01 },
      neck: { min: 0.70, max: 1.40, step: 0.02 },
      neckDepth: { min: 0.70, max: 1.40, step: 0.02 },
      neckLength: { min: 0.80, max: 1.30, step: 0.01 },
      shoulderWidth: { min: 0.75, max: 2.50, step: 0.01 },
      torsoLength: { min: 0.75, max: 1.35, step: 0.01 },
      torsoThickness: { min: 0.70, max: 1.40, step: 0.01 },
      waist: { min: 0.50, max: 1.40, step: 0.02 },
      belly: { min: 0.70, max: 2.00, step: 0.01 },
      hips: { min: 0.70, max: 1.50, step: 0.02 },
      buttocks: { min: 0.70, max: 1.50, step: 0.01 },
      buttocksThickness: { min: 0.70, max: 1.20, step: 0.01 },
      buttocksPitch: { min: -0.20, max: 0.20, step: 0.01 },
      buttocksSpread: { min: -0.05, max: 0.08, step: 0.002 },
      bust: { min: 0.60, max: 2.20, step: 0.02 },
      bustThickness: { min: 0.60, max: 1.80, step: 0.02 },
      bustPitch: { min: -0.30, max: 0.30, step: 0.01 },
      bustSpread: { min: -0.04, max: 0.06, step: 0.002 },
      arms: { min: 0.70, max: 1.40, step: 0.02 },
      armLength: { min: 0.80, max: 1.20, step: 0.01 },
      hands: { min: 0.70, max: 1.30, step: 0.01 },
      fingerWidth: { min: 0.60, max: 1.50, step: 0.02 },
      thighs: { min: 0.70, max: 1.60, step: 0.02 },
      thighLength: { min: 0.80, max: 1.30, step: 0.01 },
      calves: { min: 0.70, max: 1.50, step: 0.02 },
      calfLength: { min: 0.80, max: 1.30, step: 0.01 },
      feet: { min: 0.70, max: 1.30, step: 0.01 },
    },
  },
  wardrobe: {
    categories: [
      { id: 'clothing', label: 'panel.partCategories.clothing', icon: '👗' },
      { id: 'accessory', label: 'panel.partCategories.accessory', icon: '👓' },
      { id: 'hair', label: 'panel.partCategories.hair', icon: '💇‍♀️' },
      { id: 'face', label: 'panel.partCategories.face', icon: '🎭' },
      { id: 'body', label: 'panel.partCategories.body', icon: '🧍‍♀️' },
    ] as ModelPartCategoryDefinition[],
    parts: [
      { id: 'tops', category: 'clothing', label: 'panel.partItems.tops', icon: '👚', defaultVisible: true },
      { id: 'bottoms', category: 'clothing', label: 'panel.partItems.bottoms', icon: '👖', defaultVisible: true },
      { id: 'dress', category: 'clothing', label: 'panel.partItems.dress', icon: '👗', defaultVisible: true },
      { id: 'neckwear', category: 'clothing', label: 'panel.partItems.neckwear', icon: '👔', defaultVisible: true },
      { id: 'armwear', category: 'clothing', label: 'panel.partItems.armwear', icon: '🧤', defaultVisible: true },
      { id: 'inner_top', category: 'clothing', label: 'panel.partItems.inner_top', icon: '🩱', defaultVisible: true },
      { id: 'inner_bottom', category: 'clothing', label: 'panel.partItems.inner_bottom', icon: '🩲', defaultVisible: true },
      { id: 'legwear', category: 'clothing', label: 'panel.partItems.legwear', icon: '🧦', defaultVisible: true },
      { id: 'shoes', category: 'clothing', label: 'panel.partItems.shoes', icon: '👟', defaultVisible: true },
      { id: 'accessory', category: 'accessory', label: 'panel.partItems.accessory', icon: '👓', defaultVisible: true },
      { id: 'hair_front', category: 'hair', label: 'panel.partItems.hair_front', icon: '🎀', defaultVisible: true },
      { id: 'hair_main', category: 'hair', label: 'panel.partItems.hair_main', icon: '💇‍♀️', defaultVisible: true },
      { id: 'hair_back', category: 'hair', label: 'panel.partItems.hair_back', icon: '💆‍♀️', defaultVisible: true },
      { id: 'face_skin', category: 'face', label: 'panel.partItems.face_skin', icon: '👧', defaultVisible: true },
      { id: 'face_brows', category: 'face', label: 'panel.partItems.face_brows', icon: '🤨', defaultVisible: true },
      { id: 'face_eyelines', category: 'face', label: 'panel.partItems.face_eyelines', icon: '👁️', defaultVisible: true },
      { id: 'face_highlights', category: 'face', label: 'panel.partItems.face_highlights', icon: '✨', defaultVisible: true },
      { id: 'face_irises', category: 'face', label: 'panel.partItems.face_irises', icon: '🟣', defaultVisible: true },
      { id: 'face_mouth', category: 'face', label: 'panel.partItems.face_mouth', icon: '👄', defaultVisible: true },
      { id: 'body_skin', category: 'body', label: 'panel.partItems.body_skin', icon: '🧍‍♀️', defaultVisible: true },
    ] as ModelPartDefinition[],
    defaultVisibility: {
      tops: true,
      bottoms: true,
      dress: true,
      neckwear: true,
      armwear: true,
      inner_top: true,
      inner_bottom: true,
      legwear: true,
      shoes: true,
      accessory: true,
      hair_front: true,
      hair_main: true,
      hair_back: true,
      face_skin: true,
      face_brows: true,
      face_eyelines: true,
      face_highlights: true,
      face_irises: true,
      face_mouth: true,
      body_skin: true,
    } as Record<string, boolean>,
  },
  expressions: [
    { key: 'neutral' },
    { key: 'happy' },
    { key: 'angry' },
    { key: 'sad' },
    { key: 'relaxed' },
    { key: 'surprised' },
  ],
  dev: {
    disableLoadingOverlayInDev: true,
  },
} as const;

export type AppConfig = typeof APP_CONFIG;
